"""Default governed block catalog v0.2.5 (ADR 0047). Declarative only."""

from __future__ import annotations

from oec.neural.architecture.adapters import ADAPTER_SPECS
from oec.neural.architecture.registry import BlockRegistry
from oec.neural.architecture.specs import BlockParameterSpec, BlockSpec
from oec.neural.architecture.types import BlockCategory, NeuralFamily, TensorKind

BASE_BLOCKS = (
    BlockSpec(
        id="linear",
        display_name="Linear",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.PRIMITIVE,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", required=True, minimum=1),
            BlockParameterSpec(name="bias", kind="bool", default=True),
            BlockParameterSpec(
                name="activation",
                kind="enum",
                default="none",
                choices=("relu", "gelu", "silu", "mish", "tanh", "none"),
            ),
        ),
        capabilities=frozenset({"dense", "projection"}),
        experimental=False,
    ),
    BlockSpec(
        id="mlp",
        display_name="MLP Block",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=128, minimum=8),
            BlockParameterSpec(name="out_features", kind="int", minimum=1),
            BlockParameterSpec(
                name="activation",
                kind="enum",
                default="gelu",
                choices=("relu", "gelu", "silu", "mish", "tanh"),
            ),
        ),
        capabilities=frozenset({"dense"}),
        experimental=False,
    ),
    BlockSpec(
        id="residual_mlp",
        display_name="Residual MLP",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
        ),
        capabilities=frozenset({"dense", "residual"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="swiglu",
        display_name="SwiGLU",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=128, minimum=8),
        ),
        capabilities=frozenset({"gated"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="conv1d",
        display_name="Conv1D Block",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.IMAGE_1D, TensorKind.FEATURE_MAP_1D}),
        output_kind=TensorKind.FEATURE_MAP_1D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field"}),
        experimental=False,
    ),
    BlockSpec(
        id="conv2d",
        display_name="Conv2D Block",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.IMAGE_2D, TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field"}),
        experimental=False,
    ),
    BlockSpec(
        id="lstm",
        display_name="LSTM",
        family=NeuralFamily.RECURRENT,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=1, minimum=1),
        ),
        capabilities=frozenset({"recurrent", "gated"}),
        experimental=False,
    ),
    BlockSpec(
        id="gru",
        display_name="GRU",
        family=NeuralFamily.RECURRENT,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=1, minimum=1),
        ),
        capabilities=frozenset({"recurrent", "gated"}),
        experimental=False,
    ),
    BlockSpec(
        id="tcn",
        display_name="Temporal Convolutional Network Block",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=32, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"temporal", "dilated_conv"}),
        experimental=False,
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="self_attention",
        display_name="Self Attention",
        family=NeuralFamily.ATTENTION,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="d_model", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="nhead", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"attention"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="transformer_encoder",
        display_name="Transformer Encoder",
        family=NeuralFamily.TRANSFORMER,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="d_model", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="nhead", kind="int", default=2, minimum=1),
            BlockParameterSpec(name="dim_feedforward", kind="int", default=32, minimum=1),
            BlockParameterSpec(name="num_layers", kind="int", default=1, minimum=1),
        ),
        capabilities=frozenset({"attention", "residual", "feedforward"}),
        experimental=False,
    ),
    BlockSpec(
        id="kan",
        display_name="KAN Block",
        family=NeuralFamily.KAN,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(
                name="basis",
                kind="enum",
                default="bspline",
                choices=("bspline", "rbf"),
            ),
            BlockParameterSpec(name="grid_size", kind="int", default=8, minimum=2, maximum=128),
        ),
        capabilities=frozenset({"functional_edges"}),
        backend_requirements=("torch",),
        experimental=True,
        notes="Honest B-spline/RBF basis KAN layer; no MLP+GELU stand-in.",
    ),
    BlockSpec(
        id="gcn",
        display_name="Graph Convolutional Network",
        family=NeuralFamily.GRAPH,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.GRAPH, TensorKind.NODE_FEATURES}),
        output_kind=TensorKind.NODE_FEATURES,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"message_passing"}),
        experimental=False,
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="graphsage",
        display_name="GraphSAGE",
        family=NeuralFamily.GRAPH,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.GRAPH, TensorKind.NODE_FEATURES}),
        output_kind=TensorKind.NODE_FEATURES,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"message_passing", "aggregation"}),
        experimental=False,
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="gat",
        display_name="Graph Attention Network",
        family=NeuralFamily.GRAPH,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.GRAPH, TensorKind.NODE_FEATURES}),
        output_kind=TensorKind.NODE_FEATURES,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1),
            BlockParameterSpec(name="heads", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"message_passing", "attention"}),
        experimental=False,
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="encoder",
        display_name="Encoder Motif",
        family=NeuralFamily.AUTOENCODER,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.LATENT,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"representation_learning"}),
        experimental=False,
    ),
    BlockSpec(
        id="decoder",
        display_name="Decoder Motif",
        family=NeuralFamily.AUTOENCODER,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.LATENT}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"reconstruction"}),
        experimental=False,
    ),
)

# Wave A6 — expanded catalog (declarative; many backends still future).
A6_BLOCKS = (
    BlockSpec(
        id="geglu",
        display_name="GEGLU",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
        ),
        capabilities=frozenset({"gated"}),
        backend_requirements=("torch",),
        notes="Rank-preserving gated unit; VECTOR is not a silent SEQUENCE.",
    ),
    BlockSpec(
        id="residual_gated",
        display_name="Residual Gated",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),),
        capabilities=frozenset({"gated", "residual"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="highway",
        display_name="Highway",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),),
        capabilities=frozenset({"gated"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="depthwise_conv2d",
        display_name="Depthwise Conv2D",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.IMAGE_2D, TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field", "depthwise"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="separable_conv2d",
        display_name="Separable Conv2D",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.IMAGE_2D, TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field", "separable"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="dilated_conv1d",
        display_name="Dilated Conv1D",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.FEATURE_MAP_1D, TensorKind.SEQUENCE}),
        output_kind=TensorKind.FEATURE_MAP_1D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
            BlockParameterSpec(name="dilation", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"dilated_conv"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="grouped_conv2d",
        display_name="Grouped Conv2D",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.IMAGE_2D, TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
            BlockParameterSpec(name="groups", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field", "grouped"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="squeeze_excitation",
        display_name="Squeeze-and-Excitation",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="reduction", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"channel_attention"}),
        backend_requirements=("torch",),
    ),
    BlockSpec(
        id="cross_attention",
        display_name="Cross Attention",
        family=NeuralFamily.ATTENTION,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        input_ports=("query", "context"),
        parameters=(
            BlockParameterSpec(name="d_model", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="nhead", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"attention", "cross"}),
        backend_requirements=("torch",),
        notes="Named ports required; unary sequential edges fail closed.",
    ),
    BlockSpec(
        id="local_attention",
        display_name="Local Attention",
        family=NeuralFamily.ATTENTION,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="d_model", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="nhead", kind="int", default=2, minimum=1),
            BlockParameterSpec(name="window", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"attention", "local"}),
        backend_requirements=("torch",),
        notes="Block-local windowed attention; not global.",
    ),
    BlockSpec(
        id="linear_attention",
        display_name="Linear Attention",
        family=NeuralFamily.ATTENTION,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="d_model", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="nhead", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"attention", "linear"}),
        backend_requirements=("torch",),
        notes="Feature-map linear attention (ELU+1); not softmax attention.",
    ),
    BlockSpec(
        id="neural_ode",
        display_name="Neural ODE Motif",
        family=NeuralFamily.CONTINUOUS,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="steps", kind="int", default=4, minimum=1, maximum=64),
        ),
        capabilities=frozenset({"continuous_dynamics"}),
        backend_requirements=("torch",),
        experimental=True,
        notes="Fixed-step Euler residual ODE. Not adaptive dopri5.",
    ),
    BlockSpec(
        id="fno",
        display_name="Fourier Neural Operator 1D",
        family=NeuralFamily.NEURAL_OPERATOR,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.FEATURE_MAP_1D}),
        output_kind=TensorKind.FEATURE_MAP_1D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="modes", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"spectral"}),
        backend_requirements=("torch",),
        experimental=True,
        notes="rfft -> truncated-mode linear -> irfft; rank preserving. Use fno_2d for 2D.",
    ),
    BlockSpec(
        id="fno_2d",
        display_name="Fourier Neural Operator 2D",
        family=NeuralFamily.NEURAL_OPERATOR,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="modes", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"spectral"}),
        backend_requirements=("torch",),
        experimental=True,
        notes="rfft2 -> truncated-mode linear -> irfft2; rank preserving.",
    ),
    BlockSpec(
        id="deeponet",
        display_name="DeepONet",
        family=NeuralFamily.NEURAL_OPERATOR,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        input_ports=("branch", "trunk"),
        parameters=(
            BlockParameterSpec(name="branch_dim", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="trunk_dim", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="p", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
        ),
        capabilities=frozenset({"operator"}),
        backend_requirements=("torch",),
        experimental=True,
        notes="Branch/trunk inner-product DeepONet. Named ports required.",
    ),
    BlockSpec(
        id="pinn_motif",
        display_name="PINN Motif",
        family=NeuralFamily.PHYSICS_INFORMED,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1, maximum=8),
        ),
        capabilities=frozenset({"physics_informed"}),
        backend_requirements=("torch",),
        experimental=True,
        notes="MLP motif only. PDE residual/collocation loss is not this IR.",
    ),
)

# Zip v0.1 leftovers (A2/A6/macros) — catalog 0.2.5.
ZIP_LEFTOVER_BLOCKS = (
    BlockSpec(
        id="glu",
        display_name="GLU",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
        ),
        capabilities=frozenset({"gated"}),
        backend_requirements=("torch", "jax"),
        notes="Sigmoid-gated linear unit; rank-preserving.",
    ),
    BlockSpec(
        id="residual_conv",
        display_name="Residual Conv2D",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.IMAGE_2D, TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field", "residual"}),
        backend_requirements=("torch", "jax"),
    ),
    BlockSpec(
        id="conv3d",
        display_name="Conv3D Block",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VOLUME_3D, TensorKind.FEATURE_MAP_3D}),
        output_kind=TensorKind.FEATURE_MAP_3D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=1, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="kernel_size", kind="int", default=3, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field"}),
        backend_requirements=("torch", "jax"),
    ),
    BlockSpec(
        id="hybrid_kan",
        display_name="Hybrid KAN/MLP",
        family=NeuralFamily.KAN,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(
                name="basis",
                kind="enum",
                default="bspline",
                choices=("bspline", "rbf"),
            ),
            BlockParameterSpec(name="grid_size", kind="int", default=8, minimum=2, maximum=128),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
        ),
        capabilities=frozenset({"functional_edges", "dense"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Parallel KAN (bspline/rbf) and MLP paths, summed. Not a third basis.",
    ),
    BlockSpec(
        id="lif_spike",
        display_name="LIF Spike",
        family=NeuralFamily.SPIKING,
        category=BlockCategory.BLOCK,
        input_kinds=frozenset({TensorKind.VECTOR, TensorKind.SEQUENCE}),
        output_kind=TensorKind.SEQUENCE,
        parameters=(
            BlockParameterSpec(name="features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="threshold", kind="float", default=1.0, minimum=0.0),
            BlockParameterSpec(name="decay", kind="float", default=0.9, minimum=0.0, maximum=1.0),
        ),
        capabilities=frozenset({"spiking"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Discrete-time LIF unroll. VECTOR is treated as T=1. Not a SNN library.",
    ),
    BlockSpec(
        id="residual_stack",
        display_name="Residual Stack",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1, maximum=8),
        ),
        capabilities=frozenset({"dense", "residual"}),
        backend_requirements=("torch", "jax"),
    ),
    BlockSpec(
        id="bottleneck",
        display_name="Bottleneck",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"dense"}),
        backend_requirements=("torch", "jax"),
        notes="in → hidden → in. hidden is the squeezed width.",
    ),
    BlockSpec(
        id="inception",
        display_name="Inception Branch",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.IMAGE_2D, TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field", "multi_branch"}),
        backend_requirements=("torch", "jax"),
        notes="Internal 1x1/3x3/5x5 concat then 1x1 project. Graph-level forks still fail A7.",
    ),
    BlockSpec(
        id="dense_block",
        display_name="Dense Connectivity",
        family=NeuralFamily.CONVOLUTIONAL,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.FEATURE_MAP_2D}),
        output_kind=TensorKind.FEATURE_MAP_2D,
        parameters=(
            BlockParameterSpec(name="in_channels", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="growth_rate", kind="int", default=4, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1, maximum=8),
            BlockParameterSpec(name="out_channels", kind="int", default=8, minimum=1),
        ),
        capabilities=frozenset({"local_receptive_field", "dense_connectivity"}),
        backend_requirements=("torch", "jax"),
        notes="Concat growth maps then 1x1 to out_channels. Not a full DenseNet.",
    ),
    BlockSpec(
        id="fusion",
        display_name="Multi-Branch Fusion",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        input_ports=("a", "b"),
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
        ),
        capabilities=frozenset({"fusion"}),
        backend_requirements=("torch", "jax"),
        notes="Named ports a/b concatenated then projected. Unary sequential edges fail closed.",
    ),
    BlockSpec(
        id="message_passing_stack",
        display_name="Message Passing Stack",
        family=NeuralFamily.GRAPH,
        category=BlockCategory.MOTIF,
        input_kinds=frozenset({TensorKind.GRAPH, TensorKind.NODE_FEATURES}),
        output_kind=TensorKind.NODE_FEATURES,
        parameters=(
            BlockParameterSpec(name="input_size", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="n_layers", kind="int", default=2, minimum=1),
        ),
        capabilities=frozenset({"message_passing"}),
        backend_requirements=("torch",),
        notes="Residual GCN stack. Requires edge_index. JAX not in this cut.",
    ),
    BlockSpec(
        id="encoder_decoder",
        display_name="Encoder-Decoder",
        family=NeuralFamily.AUTOENCODER,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="latent_dim", kind="int", default=4, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
        ),
        capabilities=frozenset({"representation_learning"}),
        backend_requirements=("torch", "jax"),
    ),
    BlockSpec(
        id="vae",
        display_name="VAE",
        family=NeuralFamily.AUTOENCODER,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="latent_dim", kind="int", default=4, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
        ),
        capabilities=frozenset({"representation_learning", "variational"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Reparameterized reconstruction. KL is not this IR; module.kl is diagnostic only.",
    ),
    BlockSpec(
        id="gan_generator",
        display_name="GAN Generator",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR, TensorKind.LATENT}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
        ),
        capabilities=frozenset({"generative"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Latent→data MLP. Adversarial loss is not this IR.",
    ),
    BlockSpec(
        id="gan_discriminator",
        display_name="GAN Discriminator",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=1, minimum=1),
        ),
        capabilities=frozenset({"generative"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Data→logit. Adversarial loss is not this IR.",
    ),
    BlockSpec(
        id="moe",
        display_name="Mixture of Experts",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="n_experts", kind="int", default=4, minimum=2, maximum=16),
        ),
        capabilities=frozenset({"mixture"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Softmax-gated expert MLPs, dense mix. Not top-k sparse routing.",
    ),
    BlockSpec(
        id="siamese",
        display_name="Siamese",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        input_ports=("left", "right"),
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="out_features", kind="int", default=1, minimum=1),
        ),
        capabilities=frozenset({"metric"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="Shared encoder, |l-r|, linear. Named ports required.",
    ),
    BlockSpec(
        id="diffusion_denoiser",
        display_name="Diffusion Denoiser",
        family=NeuralFamily.FEEDFORWARD,
        category=BlockCategory.MACRO,
        input_kinds=frozenset({TensorKind.VECTOR}),
        output_kind=TensorKind.VECTOR,
        parameters=(
            BlockParameterSpec(name="in_features", kind="int", default=8, minimum=1),
            BlockParameterSpec(name="hidden_dim", kind="int", default=16, minimum=1),
            BlockParameterSpec(name="time_dim", kind="int", default=4, minimum=1),
        ),
        capabilities=frozenset({"generative", "denoising"}),
        backend_requirements=("torch", "jax"),
        experimental=True,
        notes="One residual denoise step with sinusoidal time embed. Not a sampler.",
    ),
)


def make_default_registry() -> BlockRegistry:
    registry = BlockRegistry(version="0.2.5")
    registry.register_many(BASE_BLOCKS)
    registry.register_many(ADAPTER_SPECS)
    registry.register_many(A6_BLOCKS)
    registry.register_many(ZIP_LEFTOVER_BLOCKS)
    return registry


default_registry = make_default_registry()
default_registry.seal()
